### ISSUE TITLE
[Question] Is this alive?

### ISSUE THREAD

**Issue by aoshiken** [vikramarsid/msg_parser#50]

**Comment by vikramarsid** [comment]
@t3chn0tr0n Yes, I will be adding python3 support soon.

**Comment by t3chn0tr0n** [comment]
That will be awesome. Its a awesome project you have started!

**Comment by Ousret** [comment]
PR is now available for initial support. #90

**Comment by t3chn0tr0n** [comment]
Wow, this is great man! Keep up the good work! :)
