### ISSUE TITLE
Builds failing using Py27 & Tox

### ISSUE THREAD

**Issue by curldapps** [vikramarsid/msg_parser#80]
**Describe the bug**
Builds are failing with Tox using Py2.7 for what I presume is package compatibility. Requests for packages Sphinx==2.2.0 and py-test=5.1.2 are failing because they are not compatible with Python 2. 

**To Reproduce**
1. pip install -U tox-travis
2. tox

**Expected behavior**
Build and tests pass successfully without errors for retrieving dependencies, and compatibility with Python 3. Python 2 will be deprecated and no longer supported on pip in ~2 months. Happy to open a PR if you have insight into how to approach a fix. Potentially using futurize to create py2 and py3 compatible code?

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser N/A

**Comment by Ousret** [comment]
py3 initial support PR opened. wait&see.

**Comment by vikramarsid** [comment]
@curldapps resolved all issues. Thank you!
